### ISSUE TITLE
We really need the whole history?

### ISSUE THREAD

**Issue by alessandrocapotondi** [pulp-platform/pulp-riscv-gcc#1]
Dear all,
    we really need to keep the whole history of this repo?

I would suggest to start from a stable GCC commit, add our modification, and let the history start from that point. Each time it take so much time just to clone the whole repo.

The story is valid for all the submodules related to the compiler.

Best,
Alessandro

**Comment by haugoug** [comment]
This repo is just a mirror of greenwaves repository so this should be discussed with them.
